server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:file:./finance-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=zorvyn_super_secret_key_for_jwt_2026_finance_backend
app.jwt.expiration=86400000